module.exports = {
  ...require('./userModel'),
  ...require('./session'),
  ...require('./subjectModel'),
  ...require('./unitModel'),
  ...require('./questionModel'),
  ...require('./quizModel'),
  ...require('./paymentModel'),
  ...require('./userProductModel'),
  ...require('./performanceModel'),
  ...require('./difficultLevel'),
  ...require('./file'),
  ...require('./module'),
  ...require('./product'),
  ...require('./product_images'),
  ...require('./product_question_map'),
  ...require('./order'),
}